### ISSUE TITLE
功能增加

### ISSUE THREAD

**Issue by 24332994** [yclown/ql_jd_cookie#1]
希望增加：

1. 多账号登录功能。（手动添加或自动保存登录过的JD账号密码）

2. 自动勾选同意协议功能

3. 重置登录cookie，方便切换下一个账号登录

**Comment by yclown** [comment]
已更新

**Comment by 24332994** [comment]
哇哦~赶紧试试~！

**Comment by 24332994** [comment]
> 已更新
第一个账号登录后获取到cookie，发送青龙成功。

但是第二个账号登录获取成功后，发送青龙失败了，提示如下图：
![image](https://github.com/yclown/ql_jd_cookie/assets/17253635/f54fce88-69dc-4473-826f-53427163ca1f)

**Comment by 24332994** [comment]
第二次获取cookie信息时，cookie框内还保留上一次的cookie信息，建议点击重置登录后，自动清空cookie框内上一次的内容

**Comment by yclown** [comment]
已修改，合并在2.1里

> 第二次获取cookie信息时，cookie框内还保留上一次的cookie信息，建议点击重置登录后，自动清空cookie框内上一次的内容

**Comment by 24332994** [comment]
> 已修改，合并在2.1里
> 
> > 第二次获取cookie信息时，cookie框内还保留上一次的cookie信息，建议点击重置登录后，自动清空cookie框内上一次的内容
OK啦，正常更新~
