### ISSUE TITLE
关于多账号问题

### ISSUE THREAD

**Issue by binscor** [yclown/ql_jd_cookie#10]
![image](https://github.com/yclown/ql_jd_cookie/assets/37325821/17705742-27da-45de-8c0c-5756f3519b18)
我有多个京东账号，在往青龙面板发送cookies的时候，就只能设置一个账号，之前的手动的话多账号的ptkey和ptpin是通过&符号连接起来的，比如：pt_key=aaaa;pt_pin=1111;&pt_key=bbbb;pt_pin=2222;
现在的话似乎是无法根据pt_pin对指定的pt_key进行替换，就只能设置一个pt_key=aaaa;pt_pin=1111;

或者说是这个软件我的使用方法有问题

**Comment by binscor** [comment]
我看到了，似乎是多了一个JD_COOKIE，从来没试过多个JD_COOKIE的方式，不知道是否可行

**Comment by yclown** [comment]
> ![image](https://private-user-images.githubusercontent.com/37325821/336662117-17705742-27da-45de-8c0c-5756f3519b18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzQwMjksIm5iZiI6MTcxNzU3MzcyOSwicGF0aCI6Ii8zNzMyNTgyMS8zMzY2NjIxMTctMTc3MDU3NDItMjdkYS00NWRlLThjMGMtNTc1NmYzNTE5YjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA3NDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NzQ0MmRmZTAxYzliZDMxYTI3YWE3NzcyMjM0YTA4Mzg2YmM3MTVkNzM3YmRlYzIzOThhNDNmOGJhZjRkMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O0Xp2TuBDLtSFS2wRDLsHLrOE3dZwXO9Vr5_iYFKzas) 我有多个京东账号，在往青龙面板发送cookies的时候，就只能设置一个账号，之前的手动的话多账号的ptkey和ptpin是通过&符号连接起来的，比如：pt_key=aaaa;pt_pin=1111;&pt_key=bbbb;pt_pin=2222; 现在的话似乎是无法根据pt_pin对指定的pt_key进行替换，就只能设置一个pt_key=aaaa;pt_pin=1111;
> 
> 或者说是这个软件我的使用方法有问题

你用我这个发，不同的账号会创建多个JD_COOKIE，不会放在一个里面的，这样对脚本不影响的
