### ISSUE TITLE
可以关闭Webdriver属性,绕过Webdriver检测，实现自动输入密码，GitHub有两个参考项目

### ISSUE THREAD

**Issue by Alicil** [yclown/ql_jd_cookie#11]

**Comment by Alicil** [comment]
https://github.com/icepage/AutoUpdateJdCookie
https://github.com/zzhjj/svjdck
但是是python的

**Comment by yclown** [comment]
他这个也不是绕过，只是通过代码模拟来验证滑动验证码的，这个确实不好加

**Comment by Alicil** [comment]
自动输入密码就行，滑动验证没必要

**Comment by yclown** [comment]
> 自动输入密码就行，滑动验证没必要

可以，加上去了

**Comment by Alicil** [comment]
可以更新一下安卓的吗

**Comment by yclown** [comment]
安卓的点一下输入 会把账号自动填入吧，原先就有的
