### ISSUE TITLE
安卓版本

### ISSUE THREAD

**Issue by souprround** [yclown/ql_jd_cookie#12]
更新到青龙 账号能替换已经有的失效账号吗 每次都会再添加一个变量

**Comment by yclown** [comment]
就是更新原来的，除非是以前没有的账号，才会新增变量的

**Comment by souprround** [comment]
啊 那我试用的时候怎么一直新增变量 那我再测试下 谢谢回复

**Comment by yclown** [comment]
建议新增一个后先退出app，后面再用这个账号应该就是更新了

**Comment by uwhatsup** [comment]
大佬，请问安卓版可以增加一个 密码登录吗？ 保存多个账号密码  不用每次都手动输入

**Comment by yclown** [comment]
已经更新 账号密码使用空格分开就好

**Comment by uwhatsup** [comment]
> 已经更新 账号密码使用空格分开就好

谢谢大佬，太速度了！！！
