### ISSUE TITLE
[想法] 识别滑块 自动拖动

### ISSUE THREAD

**Issue by uwhatsup** [yclown/ql_jd_cookie#16]
有一个想法，不知道能不能实现自动化
我们定时运行软件，定时打开软件之后，
就会按照设置好的列表账号进行登录，
然后利用ddddocr 识别滑块地址，
实现自动拖动，登录并发送到青龙面板

ddddocr开源地址
https://github.com/sml2h3/ddddocr

**Comment by yclown** [comment]
这个还是搞不太定，太麻烦了

**Comment by uwhatsup** [comment]
好咧
