### ISSUE TITLE
【BUG】安卓版账号密码读取问题

### ISSUE THREAD

**Issue by uwhatsup** [yclown/ql_jd_cookie#17]
账号密码添加之后，如果密码里有 , 这种符号，重新打开软件之后，会出现密码 , 后面的字符串分行到新的一个账号里了

可能是大佬用了 ,  作为换行分割保存账号密码了？

**Comment by yclown** [comment]
你给个示例，我测一下

**Comment by uwhatsup** [comment]
比如账号 12345678910 abc,123
添加上面的账号密码是正常的，但是关闭软件 重新打开之后，加载的账号密码就乱了

**Comment by yclown** [comment]
可以了，更新了
