### ISSUE TITLE
感谢大佬，这个软件太方便了！

### ISSUE THREAD

**Issue by xfchu1988** [yclown/ql_jd_cookie#19]
提个小小建议：能否在账户配置处增加备注列，亲戚朋友的账号多了有时记不住电话，加了备注就方便查找了
![cfb3b99c73430ccef7f141d1a4d9cd6](https://github.com/user-attachments/assets/c0198b4d-1e32-4796-ad9d-875e76023c51)

**Comment by yclown** [comment]
更新了，下载最新的程序，把老的config文件覆盖过来就好

**Comment by xfchu1988** [comment]
@yclown 非常感谢，这么快！太好了
