### ISSUE TITLE
请教一下大佬，这个实现的大致原理？

### ISSUE THREAD

**Issue by kk-dark** [yclown/ql_jd_cookie#2]
大佬你好，可以简单介绍一下流程吗，我想用python实现一下这个功能，部署在内网web端。

**Comment by yclown** [comment]
基本就是通过web框架，登录京东，获取cookie信息。你想用部署在web端的话可能不好操作，主要是要通过京东的验证码这个环节

**Comment by kk-dark** [comment]
> 基本就是通过web框架，登录京东，获取cookie信息。你想用部署在web端的话可能不好操作，主要是要通过京东的验证码这个环节

好吧，感谢回答
