### ISSUE TITLE
请大佬修正bug，新版发送青龙面部后会把里面的原备注清空

### ISSUE THREAD

**Issue by xfchu1988** [yclown/ql_jd_cookie#20]
![1724058177588](https://github.com/user-attachments/assets/502eea1e-e2ac-4c9a-b929-f924bc1468c7)
建议可以替换或新增，或者不采取任何动作，软件里的备注只是为了查找方便。

**Comment by yclown** [comment]
可以了，原先是想把这边的备注传过去的，后来想想不合适

**Comment by xfchu1988** [comment]
@yclown 感谢大佬
