### ISSUE TITLE
v2.4.5无法使用

### ISSUE THREAD

**Issue by huxc573** [yclown/ql_jd_cookie#22]
v2.4.4无问题，另外两个版本应用标题的版本号都没变，还是v.2.4.2。
同时，每次点击发送到青龙，弹窗反馈都需要3秒左右才反馈，所以能不能把发送青龙结果以日志形式展示在按钮下方，如：
[08:46:45]xxx账号cookie发送成功!
[08:49:15]yyy账号cookie发送失败!!!

**Comment by yclown** [comment]
日志加上去了，反馈慢可能是你青龙服务器的问题吧

**Comment by huxc573** [comment]
> 日志加上去了，反馈慢可能是你青龙服务器的问题吧

应该是的，我用手机挂的青龙，服务器中转可能比较慢。
发送按钮逻辑能不能改下，只作本地判断，比如没有获取cookie，提示需要获取cookie。有cookie提示已发送，结果显示在日志区。
建议增加日志区就是为了快速切号发送，现在点了“发送到青龙”，还是要等3秒反应才能操作下一个号。

**Comment by yclown** [comment]
> > 日志加上去了，反馈慢可能是你青龙服务器的问题吧
> 
> 应该是的，我用手机挂的青龙，服务器中转可能比较慢。 发送按钮逻辑能不能改下，只作本地判断，比如没有获取cookie，提示需要获取cookie。有cookie提示已发送，结果显示在日志区。 建议增加日志区就是为了快速切号发送，现在点了“发送到青龙”，还是要等3秒反应才能操作下一个号。

关于向快速发送的问题，config里有个ShowReLoginSure 给他任意一个值，重新登录就不会提示确认框了
