### ISSUE TITLE
大大，账号不能自动填入了

### ISSUE THREAD

**Issue by achang-xyc** [yclown/ql_jd_cookie#23]
2.3/4都能正常实现账号自动填入，自2.5和6都不能实现账号自动填入功能了，不知是本地缓存或者啥问题，win11。

**Comment by yclown** [comment]
你选中账号后有个快速填入，你看看能不能填入账号，不自动填入可能和你网络也有关系的

**Comment by yclown** [comment]
修正了一下，你试试2.4.7能不能自动带入

**Comment by achang-xyc** [comment]
测试回来了，我是了在解压后目录和保留配置/不留配置的全复制旧版本目录下运行，都异常，体现为：选择密码登录账号后，会跳到京东个人中心得空白页面，然后马上跳回密码登录页面，不勾选自动登录也不能填入密码。网络通畅，开关梯子试过；2.4.4版本使用都ok，后面版本就无法填入密码了。
谢谢你，为爱发电，热情可赞。

**Comment by huxc573** [comment]
> 测试回来了，我是了在解压后目录和保留配置/不留配置的全复制旧版本目录下运行，都异常，体现为：选择密码登录账号后，会跳到京东个人中心得空白页面，然后马上跳回密码登录页面，不勾选自动登录也不能填入密码。网络通畅，开关梯子试过；2.4.4版本使用都ok，后面版本就无法填入密码了。 谢谢你，为爱发电，热情可赞。

我这边也是，只有2.4.4和之前的版本可以用。

**Comment by yclown** [comment]
行了，修复了试试看

**Comment by achang-xyc** [comment]
> 行了，修复了试试看
测试了，2.4.7.1>勾选自动登录，问题依旧，取消，则选择账号后需手动点快速填入，方才填入，依然会出现假的个人中心然后闪退回登录界面的问题。不知是否是你设置问题。
2.4.4的话，点一下账号，账号就自动填入，过滑块后进行登录，顺畅。
“账号就自动填入”》》》“选择账号后需手动点快速填入”。更新后很好使了，个人角度觉得选账号后即填入比较方便一些。仅是个人测试的感受和想法，软件做的很好的谢谢作者。

**Comment by huxc573** [comment]
> > 行了，修复了试试看
> > 测试了，2.4.7.1>勾选自动登录，问题依旧，取消，则选择账号后需手动点快速填入，方才填入，依然会出现假的个人中心然后闪退回登录界面的问题。不知是否是你设置问题。
> > 2.4.4的话，点一下账号，账号就自动填入，过滑块后进行登录，顺畅。
> > “账号就自动填入”》》》“选择账号后需手动点快速填入”。更新后很好使了，个人角度觉得选账号后即填入比较方便一些。仅是个人测试的感受和想法，软件做的很好的谢谢作者。

好像是初始页设置为个人中心，重置没登陆需要网络跳转一下导致的。看作者能不能改成先用"https://plogin.m.jd.com/login/login"登陆，判断登陆成功后再跳转到个人中心页。

**Comment by yclown** [comment]
> > > 行了，修复了试试看
> > > 测试了，2.4.7.1>勾选自动登录，问题依旧，取消，则选择账号后需手动点快速填入，方才填入，依然会出现假的个人中心然后闪退回登录界面的问题。不知是否是你设置问题。
> > > 2.4.4的话，点一下账号，账号就自动填入，过滑块后进行登录，顺畅。
> > > “账号就自动填入”》》》“选择账号后需手动点快速填入”。更新后很好使了，个人角度觉得选账号后即填入比较方便一些。仅是个人测试的感受和想法，软件做的很好的谢谢作者。
> 
> 好像是初始页设置为个人中心，重置没登陆需要网络跳转一下导致的。看作者能不能改成先用"[https://plogin.m.jd.com/login/login"登陆，判断登陆成功后再跳转到个人中心页。](https://plogin.m.jd.com/login/login%22%E7%99%BB%E9%99%86%EF%BC%8C%E5%88%A4%E6%96%AD%E7%99%BB%E9%99%86%E6%88%90%E5%8A%9F%E5%90%8E%E5%86%8D%E8%B7%B3%E8%BD%AC%E5%88%B0%E4%B8%AA%E4%BA%BA%E4%B8%AD%E5%BF%83%E9%A1%B5%E3%80%82)

能不能录个屏，或者截个动图，发我邮箱yclwon@163.com

**Comment by huxc573** [comment]
> > > > 行了，修复了试试看
> > > > 测试了，2.4.7.1>勾选自动登录，问题依旧，取消，则选择账号后需手动点快速填入，方才填入，依然会出现假的个人中心然后闪退回登录界面的问题。不知是否是你设置问题。
> > > > 2.4.4的话，点一下账号，账号就自动填入，过滑块后进行登录，顺畅。
> > > > “账号就自动填入”》》》“选择账号后需手动点快速填入”。更新后很好使了，个人角度觉得选账号后即填入比较方便一些。仅是个人测试的感受和想法，软件做的很好的谢谢作者。
> > 
> > 
> > 好像是初始页设置为个人中心，重置没登陆需要网络跳转一下导致的。看作者能不能改成先用"[https://plogin.m.jd.com/login/login"登陆，判断登陆成功后再跳转到个人中心页。](https://plogin.m.jd.com/login/login%22%E7%99%BB%E9%99%86%EF%BC%8C%E5%88%A4%E6%96%AD%E7%99%BB%E9%99%86%E6%88%90%E5%8A%9F%E5%90%8E%E5%86%8D%E8%B7%B3%E8%BD%AC%E5%88%B0%E4%B8%AA%E4%BA%BA%E4%B8%AD%E5%BF%83%E9%A1%B5%E3%80%82)
> 
> 能不能录个屏，或者截个动图，发我邮箱[yclwon@163.com](mailto:yclwon@163.com)

已发送，最新版本目前是偶尔能自动，偶尔不行。发送动图是不能自动的情况。

**Comment by yclown** [comment]
> > > > > 行了，修复了试试看
> > > > > 测试了，2.4.7.1>勾选自动登录，问题依旧，取消，则选择账号后需手动点快速填入，方才填入，依然会出现假的个人中心然后闪退回登录界面的问题。不知是否是你设置问题。
> > > > > 2.4.4的话，点一下账号，账号就自动填入，过滑块后进行登录，顺畅。
> > > > > “账号就自动填入”》》》“选择账号后需手动点快速填入”。更新后很好使了，个人角度觉得选账号后即填入比较方便一些。仅是个人测试的感受和想法，软件做的很好的谢谢作者。
> > > 
> > > 
> > > 好像是初始页设置为个人中心，重置没登陆需要网络跳转一下导致的。看作者能不能改成先用"[https://plogin.m.jd.com/login/login"登陆，判断登陆成功后再跳转到个人中心页。](https://plogin.m.jd.com/login/login%22%E7%99%BB%E9%99%86%EF%BC%8C%E5%88%A4%E6%96%AD%E7%99%BB%E9%99%86%E6%88%90%E5%8A%9F%E5%90%8E%E5%86%8D%E8%B7%B3%E8%BD%AC%E5%88%B0%E4%B8%AA%E4%BA%BA%E4%B8%AD%E5%BF%83%E9%A1%B5%E3%80%82)
> > 
> > 
> > 能不能录个屏，或者截个动图，发我邮箱[yclwon@163.com](mailto:yclwon@163.com)
> 
> 已发送，最新版本目前是偶尔能自动，偶尔不行。发送动图是不能自动的情况。

邮箱地址我写错了 发这个yclown@163.com

**Comment by huxc573** [comment]
> > > > > > 行了，修复了试试看
> > > > > > 测试了，2.4.7.1>勾选自动登录，问题依旧，取消，则选择账号后需手动点快速填入，方才填入，依然会出现假的个人中心然后闪退回登录界面的问题。不知是否是你设置问题。
> > > > > > 2.4.4的话，点一下账号，账号就自动填入，过滑块后进行登录，顺畅。
> > > > > > “账号就自动填入”》》》“选择账号后需手动点快速填入”。更新后很好使了，个人角度觉得选账号后即填入比较方便一些。仅是个人测试的感受和想法，软件做的很好的谢谢作者。
> > > > 
> > > > 
> > > > 好像是初始页设置为个人中心，重置没登陆需要网络跳转一下导致的。看作者能不能改成先用"[https://plogin.m.jd.com/login/login"登陆，判断登陆成功后再跳转到个人中心页。](https://plogin.m.jd.com/login/login%22%E7%99%BB%E9%99%86%EF%BC%8C%E5%88%A4%E6%96%AD%E7%99%BB%E9%99%86%E6%88%90%E5%8A%9F%E5%90%8E%E5%86%8D%E8%B7%B3%E8%BD%AC%E5%88%B0%E4%B8%AA%E4%BA%BA%E4%B8%AD%E5%BF%83%E9%A1%B5%E3%80%82)
> > > 
> > > 
> > > 能不能录个屏，或者截个动图，发我邮箱[yclwon@163.com](mailto:yclwon@163.com)
> > 
> > 
> > 已发送，最新版本目前是偶尔能自动，偶尔不行。发送动图是不能自动的情况。
> 
> 邮箱地址我写错了 发这个[yclown@163.com](mailto:yclown@163.com)

好的，重发了

**Comment by yclown** [comment]
> > > > > > > 行了，修复了试试看
> > > > > > > 测试了，2.4.7.1>勾选自动登录，问题依旧，取消，则选择账号后需手动点快速填入，方才填入，依然会出现假的个人中心然后闪退回登录界面的问题。不知是否是你设置问题。
> > > > > > > 2.4.4的话，点一下账号，账号就自动填入，过滑块后进行登录，顺畅。
> > > > > > > “账号就自动填入”》》》“选择账号后需手动点快速填入”。更新后很好使了，个人角度觉得选账号后即填入比较方便一些。仅是个人测试的感受和想法，软件做的很好的谢谢作者。
> > > > > 
> > > > > 
> > > > > 好像是初始页设置为个人中心，重置没登陆需要网络跳转一下导致的。看作者能不能改成先用"[https://plogin.m.jd.com/login/login"登陆，判断登陆成功后再跳转到个人中心页。](https://plogin.m.jd.com/login/login%22%E7%99%BB%E9%99%86%EF%BC%8C%E5%88%A4%E6%96%AD%E7%99%BB%E9%99%86%E6%88%90%E5%8A%9F%E5%90%8E%E5%86%8D%E8%B7%B3%E8%BD%AC%E5%88%B0%E4%B8%AA%E4%BA%BA%E4%B8%AD%E5%BF%83%E9%A1%B5%E3%80%82)
> > > > 
> > > > 
> > > > 能不能录个屏，或者截个动图，发我邮箱[yclwon@163.com](mailto:yclwon@163.com)
> > > 
> > > 
> > > 已发送，最新版本目前是偶尔能自动，偶尔不行。发送动图是不能自动的情况。
> > 
> > 
> > 邮箱地址我写错了 发这个[yclown@163.com](mailto:yclown@163.com)
> 
> 好的，重发了

可以了，试试新的，新的程序体积也小了。2.5这个版本

**Comment by achang-xyc** [comment]
> > > > > > > > 行了，修复了试试看
> > > > > > > > 测试了，2.4.7.1>勾选自动登录，问题依旧，取消，则选择账号后需手动点快速填入，方才填入，依然会出现假的个人中心然后闪退回登录界面的问题。不知是否是你设置问题。
> > > > > > > > 2.4.4的话，点一下账号，账号就自动填入，过滑块后进行登录，顺畅。
> > > > > > > > “账号就自动填入”》》》“选择账号后需手动点快速填入”。更新后很好使了，个人角度觉得选账号后即填入比较方便一些。仅是个人测试的感受和想法，软件做的很好的谢谢作者。
> > > > > > 
> > > > > > 
> > > > > > 好像是初始页设置为个人中心，重置没登陆需要网络跳转一下导致的。看作者能不能改成先用"[https://plogin.m.jd.com/login/login"登陆，判断登陆成功后再跳转到个人中心页。](https://plogin.m.jd.com/login/login%22%E7%99%BB%E9%99%86%EF%BC%8C%E5%88%A4%E6%96%AD%E7%99%BB%E9%99%86%E6%88%90%E5%8A%9F%E5%90%8E%E5%86%8D%E8%B7%B3%E8%BD%AC%E5%88%B0%E4%B8%AA%E4%BA%BA%E4%B8%AD%E5%BF%83%E9%A1%B5%E3%80%82)
> > > > > 
> > > > > 
> > > > > 能不能录个屏，或者截个动图，发我邮箱[yclwon@163.com](mailto:yclwon@163.com)
> > > > 
> > > > 
> > > > 已发送，最新版本目前是偶尔能自动，偶尔不行。发送动图是不能自动的情况。
> > > 
> > > 
> > > 邮箱地址我写错了 发这个[yclown@163.com](mailto:yclown@163.com)
> > 
> > 
> > 好的，重发了
> 
> 可以了，试试新的，新的程序体积也小了。2.5这个版本

> 这个体积很赞，用着也没问题，有问题就给你发邮箱哈帮你测试。
