### ISSUE TITLE
关于获取多账户京东ck问题

### ISSUE THREAD

**Issue by vulcanbaby** [yclown/ql_jd_cookie#26]
请问，要获取两个账号以上京东ck，直接点击重新登陆，会造成前面获取的京东ck失效吗？如是，如何解决？谢谢。

**Comment by yclown** [comment]
不会造成前面的失效的

**Comment by manyhelp** [comment]
@yclown 建议弄个列表展示出来，然后弄个按键《复制所有cookies》，然后自动将一个个cookies复制以&拼接。没公网的用户，可以手动丢到后台了

**Comment by yclown** [comment]
> @yclown 建议弄个列表展示出来，然后弄个按键《复制所有cookies》，然后自动将一个个cookies复制以&拼接。没公网的用户，可以手动丢到后台了

这个和公网没关系的，你青龙部署后，能访问，配置好接口信息就能发送了的

**Comment by uwhatsup** [comment]
大佬可否新增一个自定义接口，让我自己添加服务器地址，可以把ck  post到自定义地址，而不是固定post到青龙面板？ 因为我是公司的路由器挂的青龙面板，没有公网IP， 所以想通过post到其他地址，收到之后，手动填到青龙面板

**Comment by yclown** [comment]
自定义这个需求太少了，你要是向实现发到自己的程序，可以用nginx反向代理 登录和接收的接口，发到自己的地址也可以实现
