### ISSUE TITLE
建议：查询ck状态，把失效的账号红色标记，发送更新后自动恢复颜色

### ISSUE THREAD

**Issue by xfchu1988** [yclown/ql_jd_cookie#27]
另外新版增加一步“获取ck”感觉不如前一版，默认使用这个软件就是为了获取ck的呀，所以还是ck直接获取符合逻辑

**Comment by xfchu1988** [comment]
查询服务器青龙ck状态，把失效的账号红色标记，方便直接查找更换，更新发送后自动恢复颜色

**Comment by yclown** [comment]
这个失效检测的话，因为这边保存的账号密码，而那边是key+token，不好比对，自动获取可以加上去

**Comment by xfchu1988** [comment]
@yclown 能否把青龙的环境变量里的“状态”先读取过来，软件里再加一列“状态”呢？或者就是添加按钮，“青龙ck状态”，可以点击读取，也不更换颜色了，更方便的把状态为失效的ck列举或者弹出来，点击处理这些失效的账户。我不懂编程，只是一个小小的建议，见笑了，多谢大佬回复！

**Comment by yclown** [comment]
可以把失效的cookie获取到列出来，但是还是原先的问题，列出来了，你也不知道列出对应的账号是哪个，点击处理的话，也不知道处理哪一个，本来是可以考虑加点额外信息到cookie里的，这样也不好处理，主要是有些不一定就是账号密码登录的，这样也会判断不了。就是如果所有的cookie都是通过账号密码用我这个获取的，可以管理起来

**Comment by yclown** [comment]
> @yclown 能否把青龙的环境变量里的“状态”先读取过来，软件里再加一列“状态”呢？或者就是添加按钮，“青龙ck状态”，可以点击读取，也不更换颜色了，更方便的把状态为失效的ck列举或者弹出来，点击处理这些失效的账户。我不懂编程，只是一个小小的建议，见笑了，多谢大佬回复！

加了个失效获取，如果是通过我这个发的，就显示对应的账号，如果不是就显示对应的cookie自行判断，账号可以直接复制到上面，会自动筛选的

**Comment by xfchu1988** [comment]
@yclown 多谢大佬，刚看到，明天试试，我这都是亲戚朋友的账户，所有账户密码都是用您的软件管理的，现在非常方便快捷，比以前要省事多了

**Comment by achang-xyc** [comment]
我是上车的，但是自己本地也需要上号跑翻倍等任务。我上的车可以直接账密自动登录车，应该是基于模拟软件吧，车如此设置的，过一次短信过后就不需要管了。但是用作者软件经常触发短信验证，作者这个应该是基于web登录，对于不方便过短信就很麻烦，这软件要验证短信我就只好手机抓ck。

**Comment by achang-xyc** [comment]
所以提出愿景就是，我也是不懂，但是类似手机这样登录一次就不需要验证短信，这样子结合现在已经实现的功能，那就非常完美了。

**Comment by yclown** [comment]
> 所以提出愿景就是，我也是不懂，但是类似手机这样登录一次就不需要验证短信，这样子结合现在已经实现的功能，那就非常完美了。

 新问题请开一个新的issue #28  如果你通过账号密码登录需要验证手机号，是因为京东的机制，多地登录了，有风险
