### ISSUE TITLE
求助各位大佬

### ISSUE THREAD

**Issue by 545648604** [yclown/ql_jd_cookie#30]
刚开始正常用，第二天打开就这样用不了了，是什么问题
![QQ20240907-170106](https://github.com/user-attachments/assets/cc48389c-4816-4120-9286-f695ee13da11)

**Comment by yclown** [comment]
你退掉重开一下，不行就重新解压一个新的程序，配置文件复制过来就行

**Comment by 545648604** [comment]
> 你退掉重开一下，不行就重新解压一个新的程序，配置文件复制过来就行

我就是重复了几次了，每次都得重新解压打开才能用

**Comment by yclown** [comment]
你这个系统什么系统

**Comment by 545648604** [comment]
> 你这个系统什么系统

win11

**Comment by yclown** [comment]
如果出现问题 把运行目录里的JD_Get.exe.WebView2 和locales DawnCache GPUCache这些目录删一下看看

**Comment by 545648604** [comment]
> 如果出现问题 把运行目录里的JD_Get.exe.WebView2 和locales DawnCache GPUCache这些目录删一下看看

感谢大佬

**Comment by kwas2022** [comment]
隔几天就要相应的操作
