### ISSUE TITLE
获取失效cookie的小问题

### ISSUE THREAD

**Issue by 172122258** [yclown/ql_jd_cookie#31]
获取失效cookie这里 有的是显示账号  有的是显示cookie  
怎么让他显示成账号 或是账号的备注？

**Comment by yclown** [comment]
通过我这发过去的就显示账号，不是就话就显示key

**Comment by xfchu1988** [comment]
@yclown  大佬，目前显示的是账户了，如果能显示备注就好了。账户不好辨识。还有一个问题，怎么能只在失效的账户内操作呢，这样就更方便快捷了，唉，现在三天就失效，更新ck确实很麻烦。当然有了大佬的软件已经很方便了。多谢了

**Comment by xfchu1988** [comment]
我的建议是把软件中“账号配置”中的格式编译成类似青龙里的env.json格式，顺序对应青龙面板，这样是不是可以达到在账户配置中加入“状态”这个字段，然后读取失效账户时可以类似青龙面板那样，直接显示为红色禁用了，（当然需要青龙里的ck检测脚本首先检测）。然后只需要对显示为失效的账户进行更新ck。那就完美了。我不懂编程，只是外行的一种想法，见笑了

**Comment by yclown** [comment]
> 我的建议是把软件中“账号配置”中的格式编译成类似青龙里的env.json格式，顺序对应青龙面板，这样是不是可以达到在账户配置中加入“状态”这个字段，然后读取失效账户时可以类似青龙面板那样，直接显示为红色禁用了，（当然需要青龙里的ck检测脚本首先检测）。然后只需要对显示为失效的账户进行更新ck。那就完美了。我不懂编程，只是外行的一种想法，见笑了

我原先也考虑过用备注，但是有些喜欢备注写点别的，现在是把账号信息加在cookie里，你能看到通过我这个发送的cookie里有个from_jdget属性，备注就还是给单独使用青龙的方式使用，这样才不影响，保存青龙格式没用，问题就是cookie和账号密码对应不上，所以才要把账号信息也写到cookie里

**Comment by xfchu1988** [comment]
@yclown 逻辑上讲备注是应该只给使用青龙的使用。因为如果只需要抓ck，然后复制ck出去的话，很简单，软件已经够用的了。这个软件不是远程采集更新ck使用的。所以本地使用更新ck还是对应本地的青龙面板。所以更新青龙ck可以类似青龙的导入env.json格式那样更新，导入ck。账户密码可以另起一列，它只是在抓ck时使用

**Comment by xfchu1988** [comment]
@yclown 顺序是不是可以这样，利用账户密码这两列采集ck，然后比对ck中的pin对应更新。我现在明白大佬刚才回复的意思了。所以我上述的想法很难实现

**Comment by xfchu1988** [comment]
换种思路可不可以实现呢，读取失效账户是从青龙里读取后，在账户配置里的“状态”里体现，然后点击“快速填入”时，还是只填入账户密码，采集好ck后点击“发送青龙"，和现在执行的步骤一样不变。改变的只是更新了一个”状态“

**Comment by yclown** [comment]
> 换种思路可不可以实现呢，读取失效账户是从青龙里读取后，在账户配置里的“状态”里体现，然后点击“快速填入”时，还是只填入账户密码，采集好ck后点击“发送青龙"，和现在执行的步骤一样不变。改变的只是更新了一个”状态“

那现在其实也可以了，如果你都是通过这个发的，下面会显示账号，复制到上面选择对应的账号就行了

**Comment by xfchu1988** [comment]
@yclown 多谢大佬了，是我没有学会，刚才试用了你说的功能，可以实现了，很方便，只要复制一个账户到上面，就可以对应相应的账户信息了，多谢了！

**Comment by 172122258** [comment]
所以现在就只剩下一个 滑块了。。解决这个问题 就无敌了

**Comment by yclown** [comment]
> 所以现在就只剩下一个 滑块了。。解决这个问题 就无敌了

#29 有人提过了，有时间可以尝试看看能不能解决吧
