### ISSUE TITLE
发送失败:未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by AlexFang86** [yclown/ql_jd_cookie#35]
几个版本都有这个问题，请问如何解决啊，感谢。
![image](https://github.com/user-attachments/assets/b977586f-0dfa-4cb9-88fa-b4870fbc4681)

**Comment by yclown** [comment]
有个日志文件，发生错误后把日志文件的内容复制过来看看

**Comment by AlexFang86** [comment]
2024-10-25 23:43:14,756 【ERROR】 发送日志：Exception Details:
Exception Type: System.NullReferenceException
Message: 未将对象引用设置到对象的实例。
Source: JD_Get
Stack Trace:
   在 JD_Get.QLHelp.GetEnvs(String searchValue) 位置 E:\mywork\ql_jd_cookie\QLHelp.cs:行号 156
   在 JD_Get.Form1.Send(String pin, String key) 位置 E:\mywork\ql_jd_cookie\Form1.cs:行号 165

Time: 2024-10-25 15:43:14 UTC
Thread ID: 1

是这样的。

**Comment by yclown** [comment]
应该还是青龙的环境没设置好，你看看填写青龙配置的时候有个测试，测试通过了吗
