### ISSUE TITLE
windows11系统 应用窗口大小bug

### ISSUE THREAD

**Issue by xianhua347** [yclown/ql_jd_cookie#36]
### 问题：应用有几率发生窗口大小异常，AppData中的user.config文件 FormLocation 属性对应的值会变为-32000, -32000，需要删除配置文件才可以解决问题

> #30 和这个Issues问题一样

窗口大小异常配置文件：
![image](https://github.com/user-attachments/assets/0b67d9c6-0a20-4102-a0be-df51677f78bd)

窗口大小异常:
![ad1e29beb5836810fbf0b1af6da34ca](https://github.com/user-attachments/assets/93a5b89a-b298-4c5d-829d-05106407aab8)

删除配置文件后的配置文件:
![image](https://github.com/user-attachments/assets/882aad0d-20ff-4da8-830a-dc5267213acc)

**Comment by yclown** [comment]
已更新
