### ISSUE TITLE
win11不显示网页

### ISSUE THREAD

**Issue by xllxll** [yclown/ql_jd_cookie#37]
<img width="1259" alt="截屏2024-11-29 04 45 05" src="https://github.com/user-attachments/assets/f64921da-ecf5-4b8e-81d5-7af3c7399294">

**Comment by xllxll** [comment]
cef可以用

**Comment by xllxll** [comment]
另外bug ，账号总是自己自动添加空白行

**Comment by yclown** [comment]
> 另外bug ，账号总是自己自动添加空白行

win11用不了可能是你游览器的内核没有
空白行是cef版吗，有没有截图

**Comment by xllxll** [comment]
空白行是cef

**Comment by xllxll** [comment]
<img width="821" alt="截屏2024-11-29 21 59 13" src="https://github.com/user-attachments/assets/b083228b-d2d5-4863-b645-d1482a1f1be9">

**Comment by yclown** [comment]
你这个应该是换了新版本的问题，原先版本和新版本的账号保存格式不一样，重新录入一下就好

**Comment by xllxll** [comment]
好的 ，感谢大佬
