### ISSUE TITLE
在高分辨显示器上，京东的登录窗口显示不完整。。。

### ISSUE THREAD

**Issue by nethawkhu** [yclown/ql_jd_cookie#5]
默认可以调的宽一些，最好能根据DPI改动窗口尺寸和字的尺寸。谢谢！

**Comment by nethawkhu** [comment]
再提个建议，实际根本不需要获取cookie的按键吧？左侧登录成功了，右侧就直接显示出ck即可，当用户点了重新登录，同时清空之前显示的ck。或者把获取ck和发送青龙合并一下，可以少按一次按钮。

**Comment by yclown** [comment]
> 默认可以调的宽一些，最好能根据DPI改动窗口尺寸和字的尺寸。谢谢！

有没有截图，我这边没有高分辨率的设备

**Comment by nethawkhu** [comment]
![微信图片_20240410093020](https://github.com/yclown/ql_jd_cookie/assets/40261893/2b4bf798-adff-4f97-8f2f-11fdf744dcc4)


右侧的字特别小，这个问题不大，还是看的见的。
但左侧的窗口太小了，滑动验证图片的时候，左侧显示不全，所以没法滑动。我放大整个窗口的话，你限制了左侧窗口尺寸不变，仅仅是右侧尺寸变大了，所以也没用。
你可以根据系统的DPI设置自动调整一下你的窗口尺寸和文字大小。如果不这样弄，你至少可以把左侧的窗口默认的大一些，能把滑动验证图片看完整就可以了。
谢谢！

**Comment by yclown** [comment]
> ![微信图片_20240410093020](https://private-user-images.githubusercontent.com/40261893/321050436-2b4bf798-adff-4f97-8f2f-11fdf744dcc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTQ2MjIsIm5iZiI6MTcxMjcxNDMyMiwicGF0aCI6Ii80MDI2MTg5My8zMjEwNTA0MzYtMmI0YmY3OTgtYWRmZi00Zjk3LThmMmYtMTFmZGY3NDRkY2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAxNTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMDJmNTVkY2M4Y2UyODhiY2FhODU2NWNlYTUxMjkzNmMyNTNhZTIwZDU2ZjY3YzcxMTM4OTEzN2EyNjExOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dpxmb1UWxhK7Cp6AKO2wRB5U7VvN1yZzyVxO1MClqpc)
> 
> 右侧的字特别小，这个问题不大，还是看的见的。 但左侧的窗口太小了，滑动验证图片的时候，左侧显示不全，所以没法滑动。我放大整个窗口的话，你限制了左侧窗口尺寸不变，仅仅是右侧尺寸变大了，所以也没用。 你可以根据系统的DPI设置自动调整一下你的窗口尺寸和文字大小。如果不这样弄，你至少可以把左侧的窗口默认的大一些，能把滑动验证图片看完整就可以了。 谢谢！

行了，你下最新版看看
