### ISSUE TITLE
发送青龙按钮消失

### ISSUE THREAD

**Issue by a18ccms** [yclown/ql_jd_cookie#6]
![微信截图_20240410123504](https://github.com/yclown/ql_jd_cookie/assets/1287196/f83de67a-de97-473e-be12-af1dae07a572)
V2.3的发送按钮消失了。
源码貌似是2.2的。clone一份想修复。看版本貌似不是最新的2.3。不过原因好像找到了。是那个panel边界不够大挡住了。就不提交合并了。别和最新代码冲突。

**Comment by yclown** [comment]
🤦‍♂没仔细检查，现在修复了

**Comment by a18ccms** [comment]
> 🤦‍♂没仔细检查，现在修复了

感谢大佬的制作！
