### ISSUE TITLE
大佬我笔记本分辨率3072*1920 缩放200%，打开看着好累，字体太小，不知道有没有办法调整一下

### ISSUE THREAD

**Issue by xujinhui2015** [yclown/ql_jd_cookie#7]
截图看着没啥，但是现场看真的眼镜疼，就左边的浏览器窗口合适，右边的就不行
![image](https://github.com/yclown/ql_jd_cookie/assets/16284992/3be56512-35e0-47a8-be4c-5ab332894fd6)

**Comment by yclown** [comment]
你这问题我不好调试啊，没这个大的屏幕，如果你有安卓手机的话，可以试试安卓版

**Comment by yclown** [comment]
改了一点，不知道有没有用，没测过，也就没有正式版本发布了，你可以获取过去调试一下。
