### ISSUE TITLE
cookie在无法允许多设备登录

### ISSUE THREAD

**Issue by wintsa123** [yclown/ql_jd_cookie#9]
先说明，我是自己手动抓包，非作者软件。过来是想问问作者有没有遇到这种情况。
我用edge的f12移动端仿真登录后抓包，cookie能用，但第二天发现自己的手机上的jd自动退出了账号，重新登录账号后，之前抓包的cookie失效。
难道要使用中间人的方式来抓包手机的cookie？

**Comment by yclown** [comment]
现在京东的cookie有效期会比较短，可能是正常退出的情况，还有就是多账号，登陆后不要点退出，退出后会导致原先获取的cookie不能用，直接开无痕换一个窗口登录

**Comment by wintsa123** [comment]
> 现在京东的cookie有效期会比较短，可能是正常退出的情况，还有就是多账号，登陆后不要点退出，退出后会导致原先获取的cookie不能用，直接开无痕换一个窗口登录
没有点击退出，窗口是关闭了而已。但电脑网页登录后手机app会自动注销

**Comment by yclown** [comment]
> > 现在京东的cookie有效期会比较短，可能是正常退出的情况，还有就是多账号，登陆后不要点退出，退出后会导致原先获取的cookie不能用，直接开无痕换一个窗口登录
> > 没有点击退出，窗口是关闭了而已。但电脑网页登录后手机app会自动注销

你是用什么方式的登录的，正常手机上登录，然后电脑上登录后不会影响到手机的，是不是你登陆后还操作了什么
